import typescript from 'rollup-plugin-typescript2';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import terser from '@rollup/plugin-terser';

// Builds the injectable crypto bootstrap. The IIFE (noble AES-GCM + pmlSeal/pmlOpen, exposed as
// the global `__pmlCrypto`) is re-wrapped by renderChunk into a .ts that exports it as a string,
// so service_worker.ts can bake it into a mod's closure with no runtime fetch.
export default {
	input: './src/pml-crypto-entry.ts',
	output: {
		file: './src/generated/pml-crypto-bootstrap.ts',
		format: 'iife',
		name: '__pmlCrypto',
		sourcemap: false,
	},
	plugins: [
		nodeResolve(),
		typescript({ check: false, tsconfigOverride: { compilerOptions: { declaration: false } } }),
		terser(),
		{
			name: 'wrap-as-ts-string',
			renderChunk(code) {
				return '// AUTO-GENERATED by rollup.crypto.config.js — do not edit, gitignored.\n' +
					`export const PML_CRYPTO_BOOTSTRAP = ${JSON.stringify(code)}\n`;
			},
		},
	],
};
